Implement CLI
xamgore/au-software-design pull request #1
Opened 2018-05-09 21:42 UTC by xamgore

2018-05-26 16:58 UTC, yurii-litvinov requested changes
Да, теперь почти всё хорошо. Напишете комментарии ко всем классам и всем паблик-методам длиннее пары строк --- будет зачтена.

2018-05-26 16:58 UTC, yurii-litvinov commented on task01-cli/README.md
> +![](diagram.png)
Ну, сгенерённая диаграмма не очень полезна, там не вся ценная информация показана, зато куча бесполезной. Но ладно.

2018-05-26 16:58 UTC, yurii-litvinov commented on task01-cli/src/main/java/ru/xamgore/Main.java
> +public class Main {
Я бы сказал, что даже тут нужны комментарии, Вы бы сказали, что они только загромождают код и я придираюсь, я бы согласился.

2018-05-26 16:58 UTC, yurii-litvinov commented on task01-cli/src/main/java/ru/xamgore/Repl.java
> +public class Repl {
Но вот тут комментарии точно нужны.

2018-05-26 16:58 UTC, yurii-litvinov commented on task01-cli/src/main/java/ru/xamgore/Repl.java
> +  public void process(String line) {
И ко всем паблик-методам. Относитесь к этому как к правилам игры.

2018-05-26 16:58 UTC, yurii-litvinov commented on task01-cli/src/main/java/ru/xamgore/parser/ParseException.java
> +public final class ParseException extends RuntimeException {
И даже исключениям нужны комментарии

2018-05-26 16:58 UTC, yurii-litvinov commented on task01-cli/src/main/java/ru/xamgore/parser/Visitor.java
> +public interface Visitor {
И даже интерфейсам. Их документировать важнее, чем классы, потому как они по идее чаще встречаются в программе.

2018-05-27 09:15 UTC, xamgore commented on task01-cli/src/main/java/ru/xamgore/Main.java
> +public class Main {
done.

2018-05-27 09:15 UTC, xamgore commented on task01-cli/src/main/java/ru/xamgore/Repl.java
> +public class Repl {
done.

2018-05-27 09:15 UTC, xamgore commented on task01-cli/src/main/java/ru/xamgore/parser/ParseException.java
> +public final class ParseException extends RuntimeException {
done.

2018-05-27 09:15 UTC, xamgore commented on task01-cli/src/main/java/ru/xamgore/Repl.java
> +  public void process(String line) {
done.

2018-05-27 09:15 UTC, xamgore commented on task01-cli/src/main/java/ru/xamgore/parser/Visitor.java
> +public interface Visitor {
done.

2018-05-27 10:58 UTC, yurii-litvinov approved these changes
Ага, зачтена

2018-05-27 10:58 UTC, yurii-litvinov commented on task01-cli/src/main/java/ru/xamgore/parser/Parser.java
> +   * @return true if the provided input can be parsed.
Лучше
```
/**
 * Returns true if the provided input can be parsed.
 * false, for empty input.
 */
```
--- так комментарий сгенерится в общее описание класса, иначе --- только в описание метода.

2018-12-16 05:40 UTC, closed without merging